language: c

os:
  - osx

osx_image: xcode7

compiler:
  - clang

env:
  - MACOSX_DEPLOYMENT_TARGET=10.9
    VERSIONER_PERL_VERSION=5.16
    VERSIONER_PYTHON_VERSION=2.7
    vi_cv_path_python3=/usr/local/bin/python3
    vi_cv_path_plain_lua=/usr/local/bin/lua-5.1
    "CONFOPT='--with-features=huge --enable-multibyte --enable-netbeans --with-tlib=ncurses --enable-cscope --enable-perlinterp=dynamic --enable-pythoninterp=dynamic --enable-python3interp=dynamic --enable-rubyinterp=dynamic --enable-luainterp=dynamic --with-lua-prefix=/usr/local --enable-gui=macvim'"

sudo: false

before_install:
  - brew update
  - brew install python3
  - brew install lua

script:
  - NPROC=$(getconf _NPROCESSORS_ONLN)
  - ./configure $CONFOPT --enable-fail-if-missing && make -j$NPROC
  - ./src/vim --version
  - make -C src macvim-dmg

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "src/MacVim/build/Release/MacVim-7.4.dmg"
  skip_cleanup: true

# vim:set sts=2 sw=2 tw=0 et:
